version: '2.1'
services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       softweb_dev
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  eureka-server:
    image: softweb/eureka:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      backend:
        aliases:
          - "eureka-server"
  store-service:
    image: softweb/store-api:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: store
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "store-service"
  config-server:
    image: softweb/config:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEYSTORE_PASSWORD: "gth67dtg33"
      ENCRYPT_KEYSTORE_ALIAS: "config-server-key"
      ENCRYPT_KEYSTORE_SECRET: "gth67dtg33"
    networks:
      backend:
        aliases:
          - "config-server"

networks:
  backend:
    driver: bridge
    name: softweb