version: '2.1'
services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       softweb_dev
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./scripts/data_os.sql:/docker-entrypoint-initdb.d/02-data_os.sql
      - ./scripts/data_license.sql:/docker-entrypoint-initdb.d/03-data_license.sql
      - ./scripts/data_user.sql:/docker-entrypoint-initdb.d/04-data_user.sql
      - ./scripts/data_authority.sql:/docker-entrypoint-initdb.d/05-data_authority.sql
      - ./scripts/data_category.sql:/docker-entrypoint-initdb.d/06-data_category.sql
      - ./scripts/data_application.sql:/docker-entrypoint-initdb.d/07-data_application.sql
      - ./scripts/data_image.sql:/docker-entrypoint-initdb.d/08-data_image.sql
      - ./scripts/data_installer.sql:/docker-entrypoint-initdb.d/09-data_installer.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  eureka-server:
    image: softweb/eureka:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eureka-server"
  store-service:
    image: softweb/store-api:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: store
    ports:
      - "8180:8080"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "store-service"
  config-server:
    image: softweb/config:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEYSTORE_PASSWORD: "gth67dtg33"
      ENCRYPT_KEYSTORE_ALIAS: "config-server-key"
      ENCRYPT_KEYSTORE_SECRET: "gth67dtg33"
    networks:
      backend:
        aliases:
          - "config-server"
  gateway:
    image: softweb/gateway:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: gateway
    ports:
      - "8072:8072"
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

networks:
  backend:
    driver: bridge
    name: softweb