package com.softweb.api.store.model.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Set;

/**
 * An entity class containing information about supported application categories.
 * <p>
 * The class contains the identifier and the name of the category.
 *
 * @author Maksimchuk I.
 * @version 1.0
 */
@Entity
@Table(name = "category")
@Getter @Setter
@NoArgsConstructor @AllArgsConstructor
public class Category {
    /**
     * Autogenerated id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sq_category")
    @SequenceGenerator(name = "sq_category", allocationSize = 1)
    @Column(name = "id")
    private Long id;

    /**
     * Name of category
     */
    @Column(name = "name", nullable = false)
    private String name;

    @OneToMany(mappedBy = "category")
    private Set<Application> applications;

    @Override
    public String toString() {
        return "Category{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
