# Spring configs
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: store-service
          uri: lb://store-service

          predicates:
            - Path=/store/**

          filters:
            - RewritePath=/store/(?<path>.*), /$\{path}

# Actuator configs
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"